name: TomatBoot

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Checkout everything
      - uses: actions/checkout@v2

      # Setup
      - name: Install packages
        run: sudo apt install nasm gcc-mingw-w64-x86-64

      # Finally build it
      - name: Build the EFI module
        run: make

      # Once we done upload the artificat
      - uses: actions/upload-artifact@v1
        with:
          name: TomatBoot.efi
          path: out/bin/TomatBoot.efi
